exports.cekResi = require('./cekResi')
exports.meme = require('./meme')
exports.ramalanCinta = require('./ramalan')
exports.urlShortener = require('./shortener')
exports.translate = require('./translate')
exports.brainly = require('./brainly')
exports.getLocationData = require('./location')
exports.menuId = require('./menu')
exports.images = require('./images')
exports.ttp = require('./ttp')
exports.resep = require('./resep')
exports.rugapoi = require('./nekopoi')
exports.rugaapi = require('./rugaApi')
exports.toxic = require('./toxic')
exports.cariKasar = require('./kataKotor')

